services:
  app:
    build: .
    container_name: wunderland
    restart: unless-stopped
    volumes:
      - ./Ovi/files:/app/static/files # Replace
      - ./Ovi/store:/app/static/store # Replace
      - ./Ovi/screenshots:/app/static/screenshots # Replace
      - ./Ovi/news:/app/news # Replace
    networks:
      - server
    depends_on:
      - db

  db:
    image: postgres
    container_name: wunderland-db
    networks:
      - server
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./db/database.psql:/docker-entrypoint-initdb.d/database.psql

volumes:
  pgdata:

networks:
  server:
    external: true

